//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Surveya_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationRightsInRole
    {
        public System.Guid ID { get; set; }
        public System.Guid ApplicationRightID { get; set; }
        public System.DateTime DateAssigned { get; set; }
        public System.Guid UserAssigned { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public System.Guid LastUserUpdated { get; set; }
        public Nullable<System.Guid> RoleID { get; set; }
    
        public virtual Application_Rights Application_Rights { get; set; }
    }
}
