//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Surveya_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class aspnet_Membership
    {
        public System.Guid ApplicationId { get; set; }
        public System.Guid UserId { get; set; }
        public string Password { get; set; }
        public int PasswordFormat { get; set; }
        public string PasswordSalt { get; set; }
        public string MobilePIN { get; set; }
        public string Email { get; set; }
        public string LoweredEmail { get; set; }
        public string PasswordQuestion { get; set; }
        public string PasswordAnswer { get; set; }
        public bool IsApproved { get; set; }
        public bool IsLockedOut { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastLoginDate { get; set; }
        public System.DateTime LastPasswordChangedDate { get; set; }
        public System.DateTime LastLockoutDate { get; set; }
        public int FailedPasswordAttemptCount { get; set; }
        public System.DateTime FailedPasswordAttemptWindowStart { get; set; }
        public int FailedPasswordAnswerAttemptCount { get; set; }
        public System.DateTime FailedPasswordAnswerAttemptWindowStart { get; set; }
        public string Comment { get; set; }
        public string Firstnames { get; set; }
        public string Lastname { get; set; }
        public string ContactNumber { get; set; }
        public string Country { get; set; }
        public string PhysicalAddress { get; set; }
        public byte[] Photo { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<System.DateTime> PassportExpiryDate { get; set; }
        public string MedicalAidName { get; set; }
        public string MedicalAidNumber { get; set; }
        public string MedicalAidContactNumber { get; set; }
        public string BloodType { get; set; }
        public Nullable<bool> HasAllergy { get; set; }
        public string AllergyDescription { get; set; }
        public string SafetyBootsSize { get; set; }
        public string HighVisibilityVestSize { get; set; }
        public Nullable<bool> AvailableFreeCompanies { get; set; }
        public string EmergencyContact1Fullname { get; set; }
        public string EmergencyContact1ContactNumber { get; set; }
        public string EmergencyContact1Relationship { get; set; }
        public string EmergencyContact2Fullname { get; set; }
        public string EmergencyContact2ContactNumber { get; set; }
        public string EmergencyContact2Relationship { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> DateActivated { get; set; }
        public string postalCode { get; set; }
        public string city { get; set; }
    
        public virtual aspnet_Applications aspnet_Applications { get; set; }
        public virtual aspnet_Users aspnet_Users { get; set; }
    }
}
