//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Surveya_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssumeCompanyHistory
    {
        public System.Guid ID { get; set; }
        public System.Guid UserID { get; set; }
        public System.Guid CompanyID { get; set; }
        public bool CurrentSession { get; set; }
        public System.DateTime DateStarted { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
    }
}
