//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Surveya_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorizeLogin
    {
        public System.Guid ID { get; set; }
        public System.DateTime DateRequested { get; set; }
        public System.Guid UserID { get; set; }
        public string IPAdress { get; set; }
        public string Code { get; set; }
        public Nullable<bool> IsAuthorized { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
