//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Surveya_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyCart
    {
        public System.Guid ID { get; set; }
        public System.Guid CompanyPackageID { get; set; }
        public System.Guid FeatureID { get; set; }
    }
}
