//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Surveya_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRMTrader
    {
        public System.Guid ID { get; set; }
        public Nullable<bool> isStateOwned { get; set; }
        public Nullable<bool> isCrossBorderTrader { get; set; }
        public Nullable<bool> isAgreedToParticipate { get; set; }
        public string CompanyType { get; set; }
        public string OwnedManagedBy { get; set; }
        public string BusinessLocation { get; set; }
        public string SizeOfBusiness { get; set; }
        public string ProductCategory { get; set; }
        public string ParticipateFullName { get; set; }
        public string TraderName { get; set; }
        public string ParticipateEmailAddress { get; set; }
        public string ParticipatePhoneNumber { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> AssignedTo { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<bool> isScheduled { get; set; }
        public Nullable<System.DateTime> ScheduledDate { get; set; }
        public Nullable<System.Guid> ScheduledBy { get; set; }
        public Nullable<bool> isSurveyed { get; set; }
        public Nullable<System.DateTime> SurveyedDate { get; set; }
        public Nullable<System.Guid> SurveyedBy { get; set; }
        public Nullable<bool> isReScheduled { get; set; }
        public Nullable<System.DateTime> ReScheduledDate { get; set; }
        public Nullable<System.Guid> ReScheduledBy { get; set; }
        public Nullable<bool> isComplete { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<System.Guid> CompletedBy { get; set; }
        public Nullable<System.Guid> ResponseID { get; set; }
        public string Status { get; set; }
        public Nullable<int> NumberRescheduled { get; set; }
    }
}
