//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Surveya_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class DynamicReport
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> CompanyID { get; set; }
        public string ReportName { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public string UserFullName { get; set; }
        public Nullable<System.Guid> SurveyID { get; set; }
    }
}
