//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Surveya_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class DynamicReportFilter
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> DynamicReportID { get; set; }
        public string FilterName { get; set; }
        public Nullable<long> FilterCount { get; set; }
        public Nullable<System.Guid> QuestionID1 { get; set; }
        public string QuestionCondition1 { get; set; }
        public string QuestionCompareValue1 { get; set; }
        public Nullable<System.Guid> QuestionID2 { get; set; }
        public string QuestionCondition2 { get; set; }
        public string QuestionCompareValue2 { get; set; }
        public Nullable<System.Guid> QuestionID3 { get; set; }
        public string QuestionCondition3 { get; set; }
        public string QuestionCompareValue3 { get; set; }
        public Nullable<System.Guid> QuestionID4 { get; set; }
        public string QuestionCondition4 { get; set; }
        public string QuestionCompareValue4 { get; set; }
        public Nullable<System.Guid> QuestionID5 { get; set; }
        public string QuestionCondition5 { get; set; }
        public string QuestionCompareValue5 { get; set; }
        public Nullable<System.Guid> QuestionID6 { get; set; }
        public string QuestionCondition6 { get; set; }
        public string QuestionCompareValue6 { get; set; }
        public string SqlString { get; set; }
    }
}
