//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Surveya_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlobalSetting
    {
        public System.Guid ID { get; set; }
        public string SettingName { get; set; }
        public string SettingValue { get; set; }
        public bool IsEnabled { get; set; }
    }
}
