//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Surveya_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public System.Guid ID { get; set; }
        public long InvoiceNumber { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public System.Guid CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string RegistrationNumber { get; set; }
        public string VatNumber { get; set; }
        public string PhysicalAddress { get; set; }
        public System.Guid PackageID { get; set; }
        public System.Guid CompanyPackageID { get; set; }
        public string PackageName { get; set; }
        public string PurchaseOrderNumber { get; set; }
    }
}
