//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Surveya_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public System.Guid ID { get; set; }
        public string PackageName { get; set; }
        public int NumberOfSurveys { get; set; }
        public int NumberOfQuestions { get; set; }
        public int NumberOfUsers { get; set; }
        public int NumberOfResponses { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
        public Nullable<int> NumberOfProjects { get; set; }
        public Nullable<int> NumberMonthsValidFor { get; set; }
        public Nullable<long> OrderNumber { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    }
}
