//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Surveya_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentHistory
    {
        public System.Guid ID { get; set; }
        public System.Guid CompanyPackageID { get; set; }
        public Nullable<System.DateTime> DateStarted { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public string PaymentStatus { get; set; }
        public string TransactionStatus { get; set; }
        public string PayRequestID { get; set; }
        public System.Guid InvoiceID { get; set; }
        public decimal AmountPaid { get; set; }
        public string PaymentEmail { get; set; }
        public string PaymentType { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
