//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Surveya_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTeam
    {
        public System.Guid ID { get; set; }
        public System.Guid ProjectID { get; set; }
        public System.Guid UserID { get; set; }
        public System.Guid RoleID { get; set; }
        public bool CompletedRegistration { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> HasUploadedPassport { get; set; }
        public Nullable<bool> HasUploadedVisa { get; set; }
        public Nullable<bool> HasUploadedVaccinationCertificates { get; set; }
        public Nullable<bool> HasUploadedCustomsClearanceCertificates { get; set; }
        public Nullable<bool> HasUploadedETickets { get; set; }
        public Nullable<bool> HasUploadedAccommodationConfirmation { get; set; }
        public Nullable<bool> HasUploadedDriversLicense { get; set; }
    }
}
