//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Surveya_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public System.Guid ID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectDescription { get; set; }
        public string ProjectCountry { get; set; }
        public int NumberOfMembers { get; set; }
        public System.Guid UserID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> ActualStartDate { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public Nullable<System.Guid> StartedByUserID { get; set; }
        public Nullable<System.Guid> EndedByUserID { get; set; }
        public bool IsPassportNumberRequired { get; set; }
        public Nullable<bool> IsPassportExpiryDateRequired { get; set; }
        public Nullable<bool> IsMedicalAidNameRequired { get; set; }
        public Nullable<bool> IsMedicalAidNumberRequired { get; set; }
        public Nullable<bool> IsMedicalAidContactNumberRequired { get; set; }
        public Nullable<bool> IsBloodTypeRequired { get; set; }
        public Nullable<bool> IsAllergiesRequired { get; set; }
        public Nullable<bool> IsAllergiesDescriptionRequired { get; set; }
        public Nullable<bool> IsVaccinationsRequired { get; set; }
        public Nullable<bool> IsSafetyBootsRequired { get; set; }
        public Nullable<bool> IsVestRequired { get; set; }
        public Nullable<bool> IsPassportDocRequired { get; set; }
        public Nullable<bool> IsETicketDocRequired { get; set; }
        public Nullable<bool> IsVisaDocRequired { get; set; }
        public Nullable<bool> IsAccommodationDocRequired { get; set; }
        public Nullable<bool> IsVaccinationDocRequired { get; set; }
        public Nullable<bool> IsDriversLicenseDocRequired { get; set; }
        public Nullable<bool> IsCustomsClearanceDocRequired { get; set; }
        public System.Guid ProjectCompany { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string OtherInfoRequired { get; set; }
        public Nullable<bool> IsEmergencyContactOneRequired { get; set; }
        public Nullable<bool> IsEmergencyContactTwoRequired { get; set; }
    }
}
