//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Surveya_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptHistory
    {
        public System.Guid ID { get; set; }
        public System.Guid PaymentID { get; set; }
        public System.Guid CompanyPackageID { get; set; }
        public System.DateTime ReceiptDate { get; set; }
        public string ReceiptDescription { get; set; }
        public string PackageName { get; set; }
        public System.Guid CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string EmailedTo { get; set; }
        public decimal AmountPaid { get; set; }
    }
}
