//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Surveya_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respons
    {
        public System.Guid ID { get; set; }
        public System.Guid SurveyID { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsCompleted { get; set; }
        public string SurveyTitle { get; set; }
    }
}
