//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Surveya_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyaDetail
    {
        public System.Guid ID { get; set; }
        public string RegistrationNumber { get; set; }
        public string CompanyName { get; set; }
        public string Street { get; set; }
        public string Suburb { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string VatNumber { get; set; }
        public string InvoiceNote { get; set; }
        public string InvoiceTerms { get; set; }
        public string BankAccountName { get; set; }
        public string BankName { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankBranchName { get; set; }
        public string BankBranchCode { get; set; }
    }
}
