//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Surveya_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyUser
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> CompanyID { get; set; }
        public System.Guid UserID { get; set; }
        public System.Guid RoleID { get; set; }
    }
}
