//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Surveya_Application.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ReportEntities : DbContext
    {
        public ReportEntities()
            : base("name=ReportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<InvoiceLineItem> InvoiceLineItems { get; set; }
        public virtual DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectTeam> ProjectTeams { get; set; }
        public virtual DbSet<Survey> Surveys { get; set; }
        public virtual DbSet<CompanyUser> CompanyUsers { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<ActivityStream> ActivityStreams { get; set; }
    
        public virtual ObjectResult<GetDynamicReportDetails_Result> GetDynamicReportDetails(Nullable<System.Guid> reportID)
        {
            var reportIDParameter = reportID.HasValue ?
                new ObjectParameter("ReportID", reportID) :
                new ObjectParameter("ReportID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDynamicReportDetails_Result>("GetDynamicReportDetails", reportIDParameter);
        }
    
        public virtual ObjectResult<GetInvoice_Result> GetInvoice(Nullable<System.Guid> invoiceID)
        {
            var invoiceIDParameter = invoiceID.HasValue ?
                new ObjectParameter("InvoiceID", invoiceID) :
                new ObjectParameter("InvoiceID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInvoice_Result>("GetInvoice", invoiceIDParameter);
        }
    
        public virtual ObjectResult<GetInvoiceLineItem_Result> GetInvoiceLineItem(Nullable<System.Guid> invoiceID)
        {
            var invoiceIDParameter = invoiceID.HasValue ?
                new ObjectParameter("InvoiceID", invoiceID) :
                new ObjectParameter("InvoiceID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInvoiceLineItem_Result>("GetInvoiceLineItem", invoiceIDParameter);
        }
    
        public virtual ObjectResult<GetReportFilters_Result> GetReportFilters(Nullable<System.Guid> reportID)
        {
            var reportIDParameter = reportID.HasValue ?
                new ObjectParameter("ReportID", reportID) :
                new ObjectParameter("ReportID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetReportFilters_Result>("GetReportFilters", reportIDParameter);
        }
    
        public virtual ObjectResult<GetResponseSyncNumbers_Result> GetResponseSyncNumbers(Nullable<System.Guid> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetResponseSyncNumbers_Result>("GetResponseSyncNumbers", userIDParameter);
        }
    
        public virtual ObjectResult<GetSurveyDetails_Result> GetSurveyDetails(Nullable<System.Guid> surveyID)
        {
            var surveyIDParameter = surveyID.HasValue ?
                new ObjectParameter("surveyID", surveyID) :
                new ObjectParameter("surveyID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSurveyDetails_Result>("GetSurveyDetails", surveyIDParameter);
        }
    
        public virtual ObjectResult<ResponseSummaryAllQuestions_Result> ResponseSummaryAllQuestions(Nullable<System.Guid> surveyID)
        {
            var surveyIDParameter = surveyID.HasValue ?
                new ObjectParameter("surveyID", surveyID) :
                new ObjectParameter("surveyID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ResponseSummaryAllQuestions_Result>("ResponseSummaryAllQuestions", surveyIDParameter);
        }
    
        public virtual int ResponseSummaryPerQuestion(Nullable<System.Guid> surveyID, Nullable<System.Guid> questionID)
        {
            var surveyIDParameter = surveyID.HasValue ?
                new ObjectParameter("surveyID", surveyID) :
                new ObjectParameter("surveyID", typeof(System.Guid));
    
            var questionIDParameter = questionID.HasValue ?
                new ObjectParameter("questionID", questionID) :
                new ObjectParameter("questionID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ResponseSummaryPerQuestion", surveyIDParameter, questionIDParameter);
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> UpdateDynamicReportFilter(Nullable<System.Guid> filterID, string filterName, Nullable<System.Guid> q1Id, string q1Condition, string q1CompareValue, Nullable<System.Guid> q2Id, string q2Condition, string q2CompareValue, Nullable<System.Guid> q3Id, string q3Condition, string q3CompareValue, Nullable<System.Guid> q4Id, string q4Condition, string q4CompareValue, Nullable<System.Guid> q5Id, string q5Condition, string q5CompareValue, Nullable<System.Guid> q6Id, string q6Condition, string q6CompareValue, string sqlString)
        {
            var filterIDParameter = filterID.HasValue ?
                new ObjectParameter("FilterID", filterID) :
                new ObjectParameter("FilterID", typeof(System.Guid));
    
            var filterNameParameter = filterName != null ?
                new ObjectParameter("FilterName", filterName) :
                new ObjectParameter("FilterName", typeof(string));
    
            var q1IdParameter = q1Id.HasValue ?
                new ObjectParameter("q1Id", q1Id) :
                new ObjectParameter("q1Id", typeof(System.Guid));
    
            var q1ConditionParameter = q1Condition != null ?
                new ObjectParameter("q1Condition", q1Condition) :
                new ObjectParameter("q1Condition", typeof(string));
    
            var q1CompareValueParameter = q1CompareValue != null ?
                new ObjectParameter("q1CompareValue", q1CompareValue) :
                new ObjectParameter("q1CompareValue", typeof(string));
    
            var q2IdParameter = q2Id.HasValue ?
                new ObjectParameter("q2Id", q2Id) :
                new ObjectParameter("q2Id", typeof(System.Guid));
    
            var q2ConditionParameter = q2Condition != null ?
                new ObjectParameter("q2Condition", q2Condition) :
                new ObjectParameter("q2Condition", typeof(string));
    
            var q2CompareValueParameter = q2CompareValue != null ?
                new ObjectParameter("q2CompareValue", q2CompareValue) :
                new ObjectParameter("q2CompareValue", typeof(string));
    
            var q3IdParameter = q3Id.HasValue ?
                new ObjectParameter("q3Id", q3Id) :
                new ObjectParameter("q3Id", typeof(System.Guid));
    
            var q3ConditionParameter = q3Condition != null ?
                new ObjectParameter("q3Condition", q3Condition) :
                new ObjectParameter("q3Condition", typeof(string));
    
            var q3CompareValueParameter = q3CompareValue != null ?
                new ObjectParameter("q3CompareValue", q3CompareValue) :
                new ObjectParameter("q3CompareValue", typeof(string));
    
            var q4IdParameter = q4Id.HasValue ?
                new ObjectParameter("q4Id", q4Id) :
                new ObjectParameter("q4Id", typeof(System.Guid));
    
            var q4ConditionParameter = q4Condition != null ?
                new ObjectParameter("q4Condition", q4Condition) :
                new ObjectParameter("q4Condition", typeof(string));
    
            var q4CompareValueParameter = q4CompareValue != null ?
                new ObjectParameter("q4CompareValue", q4CompareValue) :
                new ObjectParameter("q4CompareValue", typeof(string));
    
            var q5IdParameter = q5Id.HasValue ?
                new ObjectParameter("q5Id", q5Id) :
                new ObjectParameter("q5Id", typeof(System.Guid));
    
            var q5ConditionParameter = q5Condition != null ?
                new ObjectParameter("q5Condition", q5Condition) :
                new ObjectParameter("q5Condition", typeof(string));
    
            var q5CompareValueParameter = q5CompareValue != null ?
                new ObjectParameter("q5CompareValue", q5CompareValue) :
                new ObjectParameter("q5CompareValue", typeof(string));
    
            var q6IdParameter = q6Id.HasValue ?
                new ObjectParameter("q6Id", q6Id) :
                new ObjectParameter("q6Id", typeof(System.Guid));
    
            var q6ConditionParameter = q6Condition != null ?
                new ObjectParameter("q6Condition", q6Condition) :
                new ObjectParameter("q6Condition", typeof(string));
    
            var q6CompareValueParameter = q6CompareValue != null ?
                new ObjectParameter("q6CompareValue", q6CompareValue) :
                new ObjectParameter("q6CompareValue", typeof(string));
    
            var sqlStringParameter = sqlString != null ?
                new ObjectParameter("sqlString", sqlString) :
                new ObjectParameter("sqlString", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("UpdateDynamicReportFilter", filterIDParameter, filterNameParameter, q1IdParameter, q1ConditionParameter, q1CompareValueParameter, q2IdParameter, q2ConditionParameter, q2CompareValueParameter, q3IdParameter, q3ConditionParameter, q3CompareValueParameter, q4IdParameter, q4ConditionParameter, q4CompareValueParameter, q5IdParameter, q5ConditionParameter, q5CompareValueParameter, q6IdParameter, q6ConditionParameter, q6CompareValueParameter, sqlStringParameter);
        }
    
        public virtual ObjectResult<GetSurveyQuestions_Result> GetSurveyQuestions(Nullable<System.Guid> surveyID)
        {
            var surveyIDParameter = surveyID.HasValue ?
                new ObjectParameter("surveyID", surveyID) :
                new ObjectParameter("surveyID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSurveyQuestions_Result>("GetSurveyQuestions", surveyIDParameter);
        }
    
        public virtual ObjectResult<GetResponse_Result> GetResponse(Nullable<System.Guid> responseID)
        {
            var responseIDParameter = responseID.HasValue ?
                new ObjectParameter("ResponseID", responseID) :
                new ObjectParameter("ResponseID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetResponse_Result>("GetResponse", responseIDParameter);
        }
    
        public virtual ObjectResult<GetSurveyQuestionStats_Result> GetSurveyQuestionStats(Nullable<System.Guid> surveyID)
        {
            var surveyIDParameter = surveyID.HasValue ?
                new ObjectParameter("SurveyID", surveyID) :
                new ObjectParameter("SurveyID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSurveyQuestionStats_Result>("GetSurveyQuestionStats", surveyIDParameter);
        }
    
        public virtual ObjectResult<GetAuditedResponses_Result> GetAuditedResponses(Nullable<System.Guid> surveyID)
        {
            var surveyIDParameter = surveyID.HasValue ?
                new ObjectParameter("SurveyID", surveyID) :
                new ObjectParameter("SurveyID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAuditedResponses_Result>("GetAuditedResponses", surveyIDParameter);
        }
    
        public virtual ObjectResult<GetSurveyaDetails_Result> GetSurveyaDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSurveyaDetails_Result>("GetSurveyaDetails");
        }
    
        public virtual ObjectResult<GetAuditedResponsesForMatrix_Result> GetAuditedResponsesForMatrix(Nullable<System.Guid> surveyID)
        {
            var surveyIDParameter = surveyID.HasValue ?
                new ObjectParameter("SurveyID", surveyID) :
                new ObjectParameter("SurveyID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAuditedResponsesForMatrix_Result>("GetAuditedResponsesForMatrix", surveyIDParameter);
        }
    
        public virtual ObjectResult<GetAuditedResponsesForMatrix_CRM_Result> GetAuditedResponsesForMatrix_CRM(Nullable<System.Guid> surveyID)
        {
            var surveyIDParameter = surveyID.HasValue ?
                new ObjectParameter("SurveyID", surveyID) :
                new ObjectParameter("SurveyID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAuditedResponsesForMatrix_CRM_Result>("GetAuditedResponsesForMatrix_CRM", surveyIDParameter);
        }
    }
}
