//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyaMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionRow
    {
        public System.Guid ID { get; set; }
        public string RowText { get; set; }
        public long Position { get; set; }
        public System.Guid GroupID { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
