//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyaMapping
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SurveyaEntities : DbContext
    {
        public SurveyaEntities()
            : base("name=SurveyaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuditedRespons> AuditedResponses { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<QuestionGroup> QuestionGroups { get; set; }
        public virtual DbSet<QuestionRow> QuestionRows { get; set; }
        public virtual DbSet<Respons> Responses { get; set; }
        public virtual DbSet<ResponseValue> ResponseValues { get; set; }
    
        public virtual ObjectResult<GetResponse_Result> GetResponse(Nullable<System.Guid> responseID)
        {
            var responseIDParameter = responseID.HasValue ?
                new ObjectParameter("ResponseID", responseID) :
                new ObjectParameter("ResponseID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetResponse_Result>("GetResponse", responseIDParameter);
        }
    
        public virtual ObjectResult<GetAuditedResponse_Result> GetAuditedResponse(Nullable<System.Guid> responseID)
        {
            var responseIDParameter = responseID.HasValue ?
                new ObjectParameter("responseID", responseID) :
                new ObjectParameter("responseID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAuditedResponse_Result>("GetAuditedResponse", responseIDParameter);
        }
    }
}
